POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "email": "test@freshclone.com",
    "name": "Test Testy"
}

###

GET http://localhost:5000/api/ticket/get-tickets
Content-Type: application/json

###

POST http://localhost:5000/api/note/add-note 
Content-Type: application/json

{
    "by": "Jose Socorro",
    "content": "This is a note really important note",
    "noteDate": "10/11/2020",
    "ticket_number": 1
}

###
POST http://localhost:5000/api/contact/create-contact
Content-Type: application/json

{
    "name": "Miami Healhty Smiles",
    "color": "#ddbbbb",
    "email": "miami@healthy.com",
    "number": "789-123-4582"
}