POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
    "username": "jose",
    "password": "jose",
    "email": "jose@freshclone.com",
    "name": "Jose Socorro"
}

###

POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "jose",
    "password": "jose"
}

###