POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
    "username": "jose",
    "password": "jose",
    "email": "jose@freshclone.com",
    "name": "Jose Socorro"
}

###

GET http://localhost:5000/api/ticket/get-tickets
Content-Type: application/json

###
